name: Sync and Compile EHGallery Rules

on:
  schedule:
    - cron: '0 18 * * *'  # 每天北京时间02:00执行
  workflow_dispatch:

permissions:
  contents: write

jobs:
  talkatone_rules:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Git user
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Install mihomo
      run: |
        version=$(curl -sL https://github.com/MetaCubeX/mihomo/releases/download/Prerelease-Alpha/version.txt)
        curl -sL "https://github.com/MetaCubeX/mihomo/releases/download/Prerelease-Alpha/mihomo-linux-amd64-${version}.gz" | \
          gunzip -c > /usr/local/bin/mihomo && chmod +x /usr/local/bin/mihomo

    - name: Fetch EHGallery Mainland Rules
      run: |
        mkdir -p rules/mihomo/EHGallery  # 确保目录存在
        # 下载 EHGallery Mainland 规则文件
        curl -sL "https://raw.githubusercontent.com/zxcvbnmip/qxlist/main/list/eh.list" -o rules/mihomo/EHGallery/eh.list
        curl -sL "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/EHGallery/EHGallery.list" -o rules/mihomo/EHGallery/eh2.list
        cat rules/mihomo/EHGallery/eh.list >> rules/mihomo/EHGallery/eh2.list

    - name: Convert EHGallery domain rules to YAML
      run: |
        # 将域名规则转换为 YAML 格式
        echo 'payload:' > rules/mihomo/EHGallery/EHGallery_Domain.yaml
        echo 'payload:' > rules/mihomo/EHGallery/EHGallery_IP.yaml
        while IFS=, read -r type value extra || [[ -n $type || -n $value ]]; do
          if [[ -n "$value" && ! "$value" =~ ^# ]]; then
            # 如果是 DOMAIN-SUFFIX 规则，前面加上 *.
            if [[ "$type" == "DOMAIN" || "$type" == "DOMAIN-SUFFIX" ]]; then
              echo "  - '+.$value'" >> rules/mihomo/EHGallery/EHGallery_Domain.yaml
            elif [[ "$type" == "IP-CIDR" ]]; then
              echo "  - '$value'" >> rules/mihomo/EHGallery/EHGallery_IP.yaml
            fi
          fi
        done < rules/mihomo/EHGallery/eh2.list
        # 合并 EHGallery.list 内容并加上前缀两个空格
        cat rules/mihomo/EHGallery/EHGallery.list | while IFS= read -r line || [[ -n $line ]]; do
          # 判断是否是 CIDR 格式
          if [[ "$line" =~ ^([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+/[0-9]+|([0-9a-fA-F:]+:+)+[0-9a-fA-F:]+/[0-9]+)$ ]]; then
            echo "  - '$line'" >> rules/mihomo/EHGallery/EHGallery_IP.yaml
          else
            echo "  - '$line'" >> rules/mihomo/EHGallery/EHGallery_Domain.yaml
          fi
        done

        # 临时文件存放去重后的内容
        domain_file=$(mktemp)
        declare -A domain_seen_lines  # 创建一个关联数组，用于去重

        # 逐行读取 EHGallery_Domain.yaml 文件并去重
        while IFS= read -r domain || [[ -n $domain ]]; do
        # 如果该行没有出现过（去重）
          if [[ -z "${domain_seen_lines["$domain"]}" ]]; then
            echo "$domain" >> "$domain_file"
            domain_seen_lines["$domain"]=1  # 标记该行已经处理过
          fi
        done < rules/mihomo/EHGallery/EHGallery_Domain.yaml
        # 用去重后的内容覆盖原文件
        mv "$domain_file" rules/mihomo/EHGallery/EHGallery_Domain.yaml

        # 去重 EHGallery_IP.yaml 文件中的重复行（不排序）
        ip_file=$(mktemp)
        declare -A ip_seen_lines
        # 逐行读取 EHGallery_IP.yaml 文件并去重
        while IFS= read -r ip || [[ -n $ip ]]; do
          # 如果该行没有出现过（去重）
          if [[ -z "${ip_seen_lines["$ip"]}" ]]; then
            echo "$ip" >> "$ip_file"
            ip_seen_lines["$ip"]=1  # 标记该行已经处理过
          fi
        done < rules/mihomo/EHGallery/EHGallery_IP.yaml
        # 用去重后的内容覆盖原文件
        mv "$ip_file" rules/mihomo/EHGallery/EHGallery_IP.yaml

    - name: Convert EHGallery domain rules to MRS
      run: |
        # 使用 mihomo 转换为 MRS 格式
        mihomo convert-ruleset domain yaml rules/mihomo/EHGallery/EHGallery_Domain.yaml rules/mihomo/EHGallery/EHGallery_Domain.mrs
        mihomo convert-ruleset ipcidr yaml rules/mihomo/EHGallery/EHGallery_IP.yaml rules/mihomo/EHGallery/EHGallery_IP.mrs

    - name: Clean up temporary files
      run: |
        # 删除临时文件，但保留 4GTV_Domain.yaml 和 4GTV_IP.yaml
        rm -f rules/mihomo/EHGallery/eh.list rules/mihomo/EHGallery/eh2.list

    - name: Commit and Push Changes
      run: |
        git add .
        git diff-index --quiet HEAD -- || (git commit -m "Updated EHGallery rules -> domain rules" && git push)