name: Sync and Compile STUN Rules

on:
  schedule:
    - cron: '0 18 * * *'  # 每天北京时间02:00执行
  workflow_dispatch:

permissions:
  contents: write

jobs:
  talkatone_rules:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Git user
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Install mihomo
      run: |
        version=$(curl -sL https://github.com/MetaCubeX/mihomo/releases/download/Prerelease-Alpha/version.txt)
        curl -sL "https://github.com/MetaCubeX/mihomo/releases/download/Prerelease-Alpha/mihomo-linux-amd64-${version}.gz" | \
          gunzip -c > /usr/local/bin/mihomo && chmod +x /usr/local/bin/mihomo

    - name: Fetch STUN Mainland Rules
      run: |
        mkdir -p rules/mihomo/STUN  # 确保目录存在
        # 下载 STUN Mainland 规则文件
        curl -sL "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/STUN/STUN.yaml" -o rules/mihomo/STUN/STUN.txt

    - name: Separate domain rules
      run: |
        # 提取域名规则并保存到 STUN-domain.list
        grep 'DOMAIN' rules/mihomo/STUN/STUN.txt | sed '/^#/d' | sed 's/^\s*-\s*//' | sed 's/^[[:space:]]*//;s/[[:space:]]*$//' > rules/mihomo/STUN/STUN_value.txt
        grep 'IP-CIDR6' rules/mihomo/STUN/STUN.txt | sed '/^#/d' | sed 's/^\s*-\s*//' | sed 's/^[[:space:]]*//;s/[[:space:]]*$//' >> rules/mihomo/STUN/STUN_value.txt

    - name: Convert STUN domain rules to YAML
      run: |
        # 将域名规则转换为 YAML 格式
        echo 'payload:' > rules/mihomo/STUN/STUN_Domain.yaml
        echo 'payload:' > rules/mihomo/STUN/STUN_IP.yaml
        while IFS=, read -r type value || [[ -n $type || -n $value ]]; do
          if [[ -n "$value" && ! "$value" =~ ^# ]]; then
            # 如果是 DOMAIN-SUFFIX 规则，前面加上 *.
            if [[ "$type" == "DOMAIN" ]]; then
              echo "  - '+.$value'" >> rules/mihomo/STUN/STUN_Domain.yaml
            elif [[ "$type" == "IP-CIDR6" ]]; then
              echo "  - '$value/32'" >> rules/mihomo/STUN/STUN_IP.yaml
            fi
          fi
        done < rules/mihomo/STUN/STUN_value.txt
        # 合并 STUN.list 内容并加上前缀两个空格
        cat rules/mihomo/STUN/STUN.list | while IFS= read -r line || [[ -n $line ]]; do
          # 判断是否是 CIDR 格式
          if [[ "$line" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+/[0-9]+$ ]]; then
            echo "  - '$line'" >> rules/mihomo/STUN/STUN_IP.yaml
          else
            echo "  - '$line'" >> rules/mihomo/STUN/STUN_Domain.yaml
          fi
        done
        
        # 临时文件存放去重后的内容
        domain_file=$(mktemp)
        declare -A domain_seen_lines  # 创建一个关联数组，用于去重

        # 逐行读取 STUN_Domain.yaml 文件并去重
        while IFS= read -r domain || [[ -n $domain ]]; do
        # 如果该行没有出现过（去重）
          if [[ -z "${domain_seen_lines["$domain"]}" ]]; then
            echo "$domain" >> "$domain_file"
            domain_seen_lines["$domain"]=1  # 标记该行已经处理过
          fi
        done < rules/mihomo/STUN/STUN_Domain.yaml
        # 用去重后的内容覆盖原文件
        mv "$domain_file" rules/mihomo/STUN/STUN_Domain.yaml

        # 去重 STUN_IP.yaml 文件中的重复行（不排序）
        ip_file=$(mktemp)
        declare -A ip_seen_lines
        # 逐行读取 STUN_IP.yaml 文件并去重
        while IFS= read -r ip || [[ -n $ip ]]; do
          # 如果该行没有出现过（去重）
          if [[ -z "${ip_seen_lines["$ip"]}" ]]; then
            echo "$ip" >> "$ip_file"
            ip_seen_lines["$ip"]=1  # 标记该行已经处理过
          fi
        done < rules/mihomo/STUN/STUN_IP.yaml
        # 用去重后的内容覆盖原文件
        mv "$ip_file" rules/mihomo/STUN/STUN_IP.yaml

    - name: Convert STUN domain rules to MRS
      run: |
        # 使用 mihomo 转换为 MRS 格式
        mihomo convert-ruleset domain yaml rules/mihomo/STUN/STUN_Domain.yaml rules/mihomo/STUN/STUN_Domain.mrs
        mihomo convert-ruleset ipcidr yaml rules/mihomo/STUN/STUN_IP.yaml rules/mihomo/STUN/STUN_IP.mrs

    - name: Clean up temporary files
      run: |
        # 删除临时文件，但保留 4GTV_Domain.yaml 和 4GTV_IP.yaml
        rm -f rules/mihomo/STUN/STUN.txt rules/mihomo/STUN/STUN_value.txt

    - name: Commit and Push Changes
      run: |
        git add .
        git diff-index --quiet HEAD -- || (git commit -m "Updated STUN rules -> domain rules" && git push)