name: Sync and Compile TikTok Rules

on:
  schedule:
    - cron: '0 18 * * *'  # 每天北京时间02:00执行
  workflow_dispatch:

permissions:
  contents: write

jobs:
  talkatone_rules:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Git user
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Install mihomo
      run: |
        version=$(curl -sL https://github.com/MetaCubeX/mihomo/releases/download/Prerelease-Alpha/version.txt)
        curl -sL "https://github.com/MetaCubeX/mihomo/releases/download/Prerelease-Alpha/mihomo-linux-amd64-${version}.gz" | \
          gunzip -c > /usr/local/bin/mihomo && chmod +x /usr/local/bin/mihomo

    - name: Fetch TikTok Rules
      run: |
        mkdir -p rules/mihomo/TikTok  # 确保目录存在
        # 下载 TikTok 规则文件
        curl -sL "https://cdn.jsdelivr.net/gh/edwdch/domain-yaml-community@master/yaml/tiktok.txt" -o rules/mihomo/TikTok/tiktok.txt
        curl -sL "https://cdn.jsdelivr.net/gh/peiyingyao/Rule-for-OCD@master/rule/Clash/TikTok/TikTok_OCD_Domain.yaml" -o rules/mihomo/TikTok/TikTok_OCD_Domain.yaml
        cat rules/mihomo/TikTok/tiktok.txt rules/mihomo/TikTok/TikTok_OCD_Domain.yaml \
          | grep -E "^\s*-\s*['\"]?.+['\"]?\s*$" \
          | sed -E "s/^\s*-\s*['\"]?([^'\"]+)['\"]?\s*$/\1/" \
          | sort -u \
          | sed "s/^/  - '/;s/$/'/" \
          > rules/mihomo/TikTok/TikTok_Domain.yaml
        # 添加 payload: 头
        sed -i '1i payload:' rules/mihomo/TikTok/TikTok_Domain.yaml

    - name: Convert TikTok domain rules to MRS
      run: |
        # 使用 mihomo 转换为 MRS 格式
        mihomo convert-ruleset domain yaml rules/mihomo/TikTok/TikTok_Domain.yaml rules/mihomo/TikTok/TikTok_Domain.mrs

    - name: Clean up temporary files
      run: |
        # 删除临时文件，但保留 4GTV_Domain.yaml 和 4GTV_IP.yaml
        rm -f rules/mihomo/TikTok/tiktok.txt rules/mihomo/TikTok/TikTok_OCD_Domain.yaml

    - name: Commit and Push Changes
      run: |
        git add .
        git diff-index --quiet HEAD -- || (git commit -m "Updated TikTok rules -> domain rules" && git push)