name: Sync and Compile WeChat Rules

on:
  schedule:
    - cron: '0 18 * * *'  # 每天北京时间02:00执行
  workflow_dispatch:

permissions:
  contents: write

jobs:
  talkatone_rules:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Git user
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Install mihomo
      run: |
        version=$(curl -sL https://github.com/MetaCubeX/mihomo/releases/download/Prerelease-Alpha/version.txt)
        curl -sL "https://github.com/MetaCubeX/mihomo/releases/download/Prerelease-Alpha/mihomo-linux-amd64-${version}.gz" | \
          gunzip -c > /usr/local/bin/mihomo && chmod +x /usr/local/bin/mihomo

    - name: Fetch WeChat Rules
      run: |
        mkdir -p rules/mihomo/WeChat  # 确保目录存在
        # 下载 WeChat 规则文件
        curl -sL "https://cdn.jsdelivr.net/gh/chinnsenn/ClashCustomRule@master/providers/wechat_domain.yaml" -o rules/mihomo/WeChat/WeChat_Domain.yaml
        curl -sL "https://cdn.jsdelivr.net/gh/chinnsenn/ClashCustomRule@master/providers/wechat_ipcidr.yaml" -o rules/mihomo/WeChat/WeChat_IP.yaml

    - name: Convert WeChat domain rules to MRS
      run: |
        # 使用 mihomo 转换为 MRS 格式
        mihomo convert-ruleset domain yaml rules/mihomo/WeChat/WeChat_Domain.yaml rules/mihomo/WeChat/WeChat_Domain.mrs
        mihomo convert-ruleset ipcidr yaml rules/mihomo/WeChat/WeChat_IP.yaml rules/mihomo/WeChat/WeChat_IP.mrs

    - name: Commit and Push Changes
      run: |
        git add .
        git diff-index --quiet HEAD -- || (git commit -m "Updated WeChat rules -> domain rules" && git push)
